Jacksonmowry/add form submit wrapper
hack4impact-utk/uw-211 pull request #102
Opened 2024-03-10 10:04 UTC by jacksonmowry

# Description

Converts the back end to now use server actions for facilitating requests from the front end.
Adds a server action to specifically handle form submission.
Adds a submit button to the review screen.
Updates the zod schema to more closely match the database schema.

Since we are now enabling server actions the jest tests are failing due to how files marked 'use server' are compiled. It appears that this has been mitigated in later versions of Next.js, so we may need to consider updating.
https://github.com/vercel/next.js/issues/53065

The front end form is missing a few fields from the original PDF,  https://github.com/orgs/hack4impact-utk/projects/4?pane=issue&itemId=55912479

## Relevant issue(s)

Closes #97 #100 

## Questions

To help reduce the size of our main `page.tsx` file, should the conversion functions I added be moved to a separate file? 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have assigned reviewers to this PR

2024-03-12 01:09 UTC, cfisher36 requested changes
looks amazing! I agree with you on moving the conversion functions to a separate file before merging this. besides that, i'll look into updating Next to resolve the issue with Jest

2024-03-12 01:09 UTC, cfisher36 commented on src/server/actions/Agencies.ts
> +  console.log(agencyId);
leftover logs

2024-03-12 01:09 UTC, cfisher36 commented on src/app/[id]/page.tsx
> +            </button> */}
leftover comments

2024-03-12 01:09 UTC, cfisher36 commented on src/app/[id]/page.tsx
> +const dayMapping: {
I agree with you that it would probably be helpful to move these conversion functions under `./src/utils/conversions.ts` or something

2024-03-23 09:35 UTC, jacksonmowry commented
Alright, refactor is done!

2024-03-25 20:08 UTC, cfisher36 approved these changes
perfect!

2024-03-25 20:08 UTC, merged