rudrapatel2003/Authenticate server actions and API endpoints
hack4impact-utk/uw-211 pull request #111
Opened 2024-03-31 20:57 UTC by RudraPatel2003

# Description
This PR makes it so that you must have a valid next-auth cookie to be able to hit a sever endpoint or call specific server actions. 

## Relevant issue(s)

#95 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have assigned reviewers to this PR

2024-04-01 20:46 UTC, cfisher36 requested changes

2024-04-01 20:46 UTC, cfisher36 commented on src/utils/auth.ts
> +  const session = getServerSession(authOptions);
needs async/await

2024-04-02 16:48 UTC, RudraPatel2003 commented on src/utils/auth.ts
> +  const session = getServerSession(authOptions);
0e51590

2024-04-02 16:52 UTC, RudraPatel2003 commented on src/app/api/agencies/route.ts
> +  await authenticateServerEndpoint();
95d05f3 I think does what you mean? What you said makes sense though; good catch on both!

2024-04-10 03:47 UTC, cfisher36 commented on src/app/api/agencies/route.ts
> +  await authenticateServerEndpoint();
was a little unclear, but I have included the changes in b70ee50

2024-04-10 03:49 UTC, cfisher36 approved these changes
looks great!

2024-04-10 03:49 UTC, merged