Rudrapatel2003/footer 15
hack4impact-utk/uw-211 pull request #30
Opened 2023-10-24 20:25 UTC by RudraPatel2003

# Description
Adds a minimal footer component based off of TurboTax

## Relevant issue(s)
- #15 

## Questions

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have assigned reviewers to this PR

2023-10-24 23:57 UTC, cfisher36 requested changes
Looks clean 😎 Only suggestion is that we probably want to stick to uw-211/src/components/Footer/index.tsx as a convention instead of uw-211/src/components/Footer.tsx

2023-10-25 19:15 UTC, alexmingzhang submitted a review, later dismissed
Good work, approved (edit: forgot to mention, make sure to do the changes as Caleb outlined above)

2023-10-26 02:30 UTC, RudraPatel2003 commented
> Looks clean 😎 Only suggestion is that we probably want to stick to uw-211/src/components/Footer/index.tsx as a convention instead of uw-211/src/components/Footer.tsx

Makes sense. Fixed in 38152c1!

2023-10-26 16:30 UTC, cfisher36 approved these changes

2023-10-26 16:30 UTC, merged